# Generated by Django 5.2.16 on 2026-07-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurantmeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantmeal',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='restaurantmeal',
            name='meal',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='RestaurantMeal',
        ),
    ]
