# Generated by Django 5.2.16 on 2026-08-02 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_mealcategory_image'),
        ('restaurants', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('hy', 'Armenian'), ('ru', 'Russian')], max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['restaurant_id', 'language'],
            },
        ),
        migrations.AddConstraint(
            model_name='restaurantmeal',
            constraint=models.UniqueConstraint(fields=('restaurant', 'meal'), name='unique_restaurant_meal'),
        ),
        migrations.AddField(
            model_name='restauranttranslation',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='restaurants.restaurant'),
        ),
        migrations.AddConstraint(
            model_name='restauranttranslation',
            constraint=models.UniqueConstraint(fields=('restaurant', 'language'), name='unique_restaurant_translation_language'),
        ),
    ]
