# Generated by Django 5.2.16 on 2026-07-16 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meal_image_meal_is_featured'),
        ('recommandiation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_calories', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('min_protein', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_rules', to='meals.meal')),
            ],
        ),
    ]
