# Generated by Django 5.2.16 on 2026-07-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meals/'),
        ),
        migrations.AddField(
            model_name='meal',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
