# Generated by Django 5.2.16 on 2026-07-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meal_image_meal_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='image',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='price',
        ),
    ]
