# Generated by Django 5.2.16 on 2026-08-01 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_meal_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('hy', 'Armenian'), ('ru', 'Russian')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='meals.mealcategory')),
            ],
            options={
                'ordering': ['meal_category_id', 'language'],
                'constraints': [models.UniqueConstraint(fields=('meal_category', 'language'), name='unique_meal_category_translation_language')],
            },
        ),
        migrations.CreateModel(
            name='MealTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('hy', 'Armenian'), ('ru', 'Russian')], max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='meals.meal')),
            ],
            options={
                'ordering': ['meal_id', 'language'],
                'constraints': [models.UniqueConstraint(fields=('meal', 'language'), name='unique_meal_translation_language')],
            },
        ),
    ]
