# Generated by Django 5.2.16 on 2026-08-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_populate_english_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meal_categories/'),
        ),
    ]
