# Generated by Django 5.2.16 on 2026-07-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('carbohydrate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fiber', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sugar', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sodium', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
