# Generated by Django 5.2.16 on 2026-08-01 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingradients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('hy', 'Armenian'), ('ru', 'Russian')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='ingradients.ingredient')),
            ],
            options={
                'ordering': ['ingredient_id', 'language'],
                'constraints': [models.UniqueConstraint(fields=('ingredient', 'language'), name='unique_ingredient_translation_language')],
            },
        ),
    ]
