"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-t0gor9cz*3+*lerex6gx1t9isjtuvi^_$5+$nog362-w+60w1q'
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = config('DEBUG', default=False, cast=bool)

# new 1405-05-07
ALLOWED_HOSTS = ["api.ginkova.com",
                 "localhost",
                 "127.0.0.1"
                 ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'common.apps.CommonConfig',                   #'common',          # add
    'accounts.apps.AccountsConfig',               #'accounts',        # add
    'users.apps.UsersConfig',                     #'users',           # add
    'health.apps.HealthConfig',                   #'health',          # add
    'nutrition.apps.NutritionConfig',             #'nutrition',       # add
    'ingradients.apps.IngradientsConfig',         #'ingradients',     # add
    'recipes.apps.RecipesConfig',                 #'recipes',         # add
    'meals.apps.MealsConfig',                     #'meals',           # add
    'orders.apps.OrdersConfig',                   #'orders',          # add
    'wallet.apps.WalletConfig',                   #'wallet',          # add
    'payments.apps.PaymentsConfig',               #'payments',        # add
    'recommandiation.apps.RecommandiationConfig', #'recommandiation', # add
    'partners.apps.PartnersConfig',               #'partners',        # add
    'dashboard.apps.DashboardConfig',             #'dashboard',       # add
    'core.apps.CoreConfig',                       #'core',            # add
    'cart.apps.CartConfig',                       #'cart',            # add
    'notifications.apps.NotificationsConfig',     #'notifications',   # add
    'restaurants.apps.RestaurantsConfig',         #'restaurants',     # add
    'corsheaders',                                #'django-cors-headers',# add
    'rest_framework',                             #'rest_frameword',  # add
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Add this line to specify the templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'fa'
LANGUAGES = [
    ('fa', 'Persian'),
    ('en', 'English'),
    ('hy', 'Armenian'),
    ('ru', 'Russian'),
]
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]
USE_I18N = True


TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # Add this line to specify the static files directory
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # Add this line to specify the media files directory
AUTH_USER_MODEL = 'accounts.User'  # Add this line to specify the custom user model

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

PAYMENT_GATEWAY = 'fake'  # Default to 'fake' if not set
ACTIVE_PAYMENT_GATEWAYS = ['fake', "mellat", "melli", "zarinpal"]  # Default to 'fake' if not set



# ----connect to React ------
CORS_ALLOWED_ORIGINS = [ 
                        "https://ginkova.com",
                        "https://www.ginkova.com",
                        "http://localhost:5173",
                        ]