# Generated by Django 5.2.16 on 2026-07-16 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_amount_remove_payment_method_and_more'),
        ('wallet', '0002_wallettransaction_order_wallettransaction_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='order',
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transaction', to='payments.payment'),
        ),
    ]
