# Generated by Django 5.2.16 on 2026-08-01 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipeingredient_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('hy', 'Armenian'), ('ru', 'Russian')], max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='recipes.recipe')),
            ],
            options={
                'ordering': ['recipe_id', 'language'],
                'constraints': [models.UniqueConstraint(fields=('recipe', 'language'), name='unique_recipe_translation_language')],
            },
        ),
    ]
