# Generated by Django 5.2.16 on 2026-07-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='consumed_by',
            field=models.CharField(choices=[('self', 'For Myself'), ('other', 'For Other Person')], default='self', max_length=10),
        ),
    ]
