# Generated by Django 5.2.16 on 2026-07-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_consumed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='meal',
        ),
    ]
