# Generated by Django 5.2.16 on 2026-07-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_restaurant_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='restaurant_meal',
        ),
    ]
