# Generated by Django 5.2.16 on 2026-07-22 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cartitem_restaurant_meal'),
        ('restaurants', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='restaurant_meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='restaurants.restaurantmeal'),
        ),
    ]
