# Generated by Django 5.2.16 on 2026-07-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthgoal',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='healthgoal',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthgoal',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='healthgoal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
