# Generated by Django 5.2.16 on 2026-08-02 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_alter_healthgoal_options_healthgoal_display_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('hy', 'Armenian'), ('ru', 'Russian')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='health.disease')),
            ],
            options={
                'ordering': ['disease_id', 'language'],
                'constraints': [models.UniqueConstraint(fields=('disease', 'language'), name='unique_disease_translation_language')],
            },
        ),
        migrations.CreateModel(
            name='HealthGoalTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('hy', 'Armenian'), ('ru', 'Russian')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='health.healthgoal')),
            ],
            options={
                'ordering': ['health_goal_id', 'language'],
                'constraints': [models.UniqueConstraint(fields=('health_goal', 'language'), name='unique_health_goal_translation_language')],
            },
        ),
    ]
