# Generated by Django 5.2.16 on 2026-07-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='meal',
        ),
    ]
