# Generated by Django 5.2.16 on 2026-07-22 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderitem_meal'),
        ('restaurants', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='restaurant_meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='restaurants.restaurantmeal'),
        ),
    ]
