# Generated by Django 5.2.16 on 2026-07-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_create_default_channels'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('event_code', 'language'), name='unique_notification_template'),
        ),
    ]
